# Generated by Django 6.1.1 on 2026-10-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_unique_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='tasks.projectfile', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='projects/', verbose_name='Файл'),
        ),
    ]
