# Generated by Django 6.1.1 on 2026-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_unique_title_project_unique_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='projects', to='tasks.projectfile', verbose_name='Файлы'),
        ),
    ]
